name: Deploy to VPS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create dummy data folder for build test
        run: mkdir -p data
      - name: Test Docker Build
        run: docker compose build

  deploy:
    runs-on: ubuntu-latest
    needs: test-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          port: 5790
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/ubuntu/qlt-eau
            git pull origin main
            docker compose up --build -d
